name: ct
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=26.4.0
  - readline=8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.1
  - tzdata=2025b
  - wcwidth=0.2.13
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - cffi==1.17.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.12
      - ellipsinator==0.3.0
      - finufft==2.4.1
      - fonttools==4.57.0
      - imageio==2.37.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - matplotlib==3.10.1
      - mri-nufft==1.2.1
      - networkx==3.5
      - numpy==2.2.4
      - opencv-python==4.11.0.86
      - phantominator==0.7.0
      - pillow==11.1.0
      - prox-tv==3.2.1
      - pycparser==2.22
      - pyparsing==3.2.3
      - pytigre==3.0.0
      - scikit-image==0.25.2
      - scipy==1.15.2
      - ssfp==1.2.0
      - tifffile==2025.6.11
      - tqdm==4.67.1

